### ISSUE TITLE
Remove usage of imp to make it compatible with Python 3.12+

### ISSUE THREAD

**Issue by KF-Art** [xuzhen/dockbarx#10]
Greetings, I am one of the maintainers of [Cereus Linux](https://github.com/CereusLinuxProject) (a Void Linux based distribution) and also the packager of dockbarx for the distribution ([template](https://github.com/CereusLinuxProject/cereus-packages/blob/master/srcpkgs/dockbarx/template) here). 

I was updating the package to 1.0-beta3. It built fine, but at the moment of running `dockx` it gave me the following error.

```
Traceback (most recent call last):
  File "/usr/bin/dockx", line 43, in <module>
    from dockbarx.applets import DockXApplets, DockXApplet
  File "/usr/lib/python3.12/site-packages/dockbarx/applets.py", line 25, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

I was trying to find out what happened and it seems that `imp` module was deprecated since Python 3.4 and was removed in Python 3.12 (which is the version Void currently uses and Arch will eventually use as well). 

Is there a way to get rid of `imp` to keep compatibility with Python 3.12 (and newer)? Thanks in advance.

Note: I'm not a Python expert.

**Comment by xuzhen** [comment]
Fixed in https://github.com/xuzhen/dockbarx/commit/ecfe511bfa74cc3f5d92448106805dbe8c90efea. Thanks for the report!
