### ISSUE TITLE
Manual install fails due to "/usr/local/share/glib-2.0/schemas"

### ISSUE THREAD

**Issue by chrismile** [xuzhen/dockbarx#11]
Hi,

First of all thanks for working on maintaining dockbarx & xfce4-dockbarx-plugin! I have recently switched from Ubuntu to Fedora and tried installing dockbarx manually (from the pygi-python3 branch using setup.py).

When running "sudo ./setup.py install", I get the following error message:

```
Error opening directory “/usr/local/share/glib-2.0/schemas”: No such file or directory
```

The directory exists on my system, but in `/usr/share/glib-2.0/schemas`, not under `/usr/local`. Does the setup script use a wrong path? Is it supposed to install DockbarX in `/usr`, not `/usr/local`?

PS:

I also got the following warnings/errors previously, but the build succeeded after calling `mkdir build/locale`:

```
build/bdist.linux-x86_64/egg/dockbarx/common.py:325: SyntaxWarning: invalid escape sequence '\ '
  file = file.replace("%20","\ ")
error: [Errno 2] No such file or directory: 'build/locale/'
```

**Comment by chrismile** [comment]
Another addendum:

With `sudo ./setup.py install --prefix=/usr`, the install seems to have run normally. However, when using `xfce4-dockbarx-plugin` (I installed it to /usr, too), I now get the following error:

```
/usr/lib/python3.12/site-packages/Dockbarx-1.0b3-py3.12.egg/dockbarx/common.py:325: SyntaxWarning: invalid escape sequence '\ '
/usr/lib/python3.12/site-packages/Dockbarx-1.0b3-py3.12.egg/dockbarx/common.py:325: SyntaxWarning: invalid escape sequence '\ '

(xfce4-panel-plug:3180): GLib-GIO-ERROR **: 18:55:29.821: Settings schema 'org.dockbarx.dockbarx' is not installed
```

Did I do something wrong during the installation process? I installed the following Fedora packages:

```
sudo dnf install libwnck3-devel glib2-devel gtk3-devel python3 python3-polib python3-cairo python3-dbus python3-xlib python3-pyxdg python3-gobject python3-pillow
```

**Comment by chrismile** [comment]
Seems like the install script put all files into `/usr/lib/python3.12/site-packages/Dockbarx-1.0b3-py3.12.egg`, and thus `org.dockbarx.dockbarx` cannot be found in `/usr/share/glib-2.0/schemas`. Do you have an idea how this problem could be fixed? I would guess this is not Fedora-specific, but affects anyone manually installing DockbarX.

PS: Even if I manually create `/usr/local/share/glib-2.0/schemas` and call `export GSETTINGS_SCHEMA_DIR="/usr/local/share/glib-2.0/schemas:${GSETTINGS_SCHEMA_DIR}"`, no file gets installed to the schemas directory. Instead, they lie in `/usr/local/lib/python3.12/site-packages/Dockbarx-1.0b3-py3.12.egg`.

**Comment by xuzhen** [comment]
setup.py was based on distutils build system but it has been removed in Python 3.12. It seems that the module with the same name provided by setuptools is not exactly the same as the previous one. I'll find an alternative this weekend.

**Comment by xuzhen** [comment]
Should be fixed in https://github.com/xuzhen/dockbarx/commit/7c78e611452e744e2172e22aa2dc4ec307aff84f.
