### ISSUE TITLE
Can't center applet with spacer as stand alone panel

### ISSUE THREAD

**Issue by bernku** [xuzhen/dockbarx#7]
In preview version i could place the clock in the  center of the panel with the 2 spacer, i still can do it but now it don't stay lock in the center it move left or right whenever  i open or close  a program
is there a way to fix it as it was before the migration.

thanks :)

**Comment by xuzhen** [comment]
Should be fixed in https://github.com/xuzhen/dockbarx/commit/ab8b856d9eb338ac83e0167573685c465204cf8b
